### ISSUE TITLE
Include dist folder in git

### ISSUE THREAD

**Issue by MineGame159** [qzole/imgui-beef#2]
I personally have my dependencies as just cloned git repos and its easy to update it that way

**Comment by qzole** [comment]
You mean the dist folder with all the object files, right?
The reason I don't want to include that in the repository is to keep it small.
I see your point, but I don't think git is the ideal solution to dependency management of binaries and putting in the obj files for windows x64 would be wouldn't actually be complete. For a complete solution it would need all the artifacts for all the configurations.

**Comment by MineGame159** [comment]
You can just put there the dll or lib files, I did that with glfw and only it adds just 4 files that are few mbs
